### ISSUE TITLE
Unit tests with Mocha and TypeScript are erroring

### ISSUE THREAD

**Issue by srepollock** [srepollock/divine-engine#24]
### What is the Issue

When running `npm test` the command line is erroring in multiple ways. 1) Mocha is complaining about running TypeScirpt written files 2) it must run the code through a transpiler to test before running through Mocha 3) the transpiler is erroring on the type of Babel being used and 4) the tests cannot run in the DOM.

This is a multi-layered issue that will take time to address and debug. Over the next few days I really have to pay attention and get this error fixed. This will take some time to look at TypeScript, Babel and module loading. I still fully do not understand and will have to research this before I can properly utilize it. I will have to start looking at StackOverflow forums and the likes because this project needs to get working sooner than later.

### How to duplicate the issue

Run `npm test` on 5a5645e to see the log error.

### Screenshots/Console output/Log files

```
> divine-engine@0.0.1 test /Users/Spencer/Documents/git/divine-engine
> mocha --opts mocha.opts

/Users/Spencer/Documents/git/divine-engine/node_modules/babel-core/lib/transformation/file/options/option-manager.js:328
        throw e;
        ^

Error: Requires Babel "^7.0.0-0", but was loaded with "6.26.3". If you are sure you have a compatible version of @babel/core, it is likely that something in your build process is loading the wrong version. Inspect the stack trace of this error to look for the first entry that doesn't mention "@babel/core" or "babel-core" to see what is calling Babel. (While processing preset: "/Users/Spencer/Documents/git/divine-engine/node_modules/@babel/preset-env/lib/index.js")
    at throwVersionError (/Users/Spencer/Documents/git/divine-engine/node_modules/@babel/helper-plugin-utils/lib/index.js:65:11)
    at Object.assertVersion (/Users/Spencer/Documents/git/divine-engine/node_modules/@babel/helper-plugin-utils/lib/index.js:13:11)
    at _default (/Users/Spencer/Documents/git/divine-engine/node_modules/@babel/preset-env/lib/index.js:150:7)
    at /Users/Spencer/Documents/git/divine-engine/node_modules/@babel/helper-plugin-utils/lib/index.js:19:12
    at /Users/Spencer/Documents/git/divine-engine/node_modules/babel-core/lib/transformation/file/options/option-manager.js:317:46
    at Array.map (<anonymous>)
    at OptionManager.resolvePresets (/Users/Spencer/Documents/git/divine-engine/node_modules/babel-core/lib/transformation/file/options/option-manager.js:275:20)
    at OptionManager.mergePresets (/Users/Spencer/Documents/git/divine-engine/node_modules/babel-core/lib/transformation/file/options/option-manager.js:264:10)
    at OptionManager.mergeOptions (/Users/Spencer/Documents/git/divine-engine/node_modules/babel-core/lib/transformation/file/options/option-manager.js:249:14)
    at OptionManager.init (/Users/Spencer/Documents/git/divine-engine/node_modules/babel-core/lib/transformation/file/options/option-manager.js:368:12)
    at compile (/Users/Spencer/Documents/git/divine-engine/node_modules/babel-register/lib/node.js:103:45)
    at loader (/Users/Spencer/Documents/git/divine-engine/node_modules/babel-register/lib/node.js:144:14)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/Spencer/Documents/git/divine-engine/node_modules/babel-register/lib/node.js:154:7)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at /Users/Spencer/Documents/git/divine-engine/node_modules/mocha/lib/mocha.js:250:27
    at Array.forEach (<anonymous>)
    at Mocha.loadFiles (/Users/Spencer/Documents/git/divine-engine/node_modules/mocha/lib/mocha.js:247:14)
    at Mocha.run (/Users/Spencer/Documents/git/divine-engine/node_modules/mocha/lib/mocha.js:576:10)
    at Object.<anonymous> (/Users/Spencer/Documents/git/divine-engine/node_modules/mocha/bin/_mocha:637:18)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:742:12)
    at startup (internal/bootstrap/node.js:266:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:596:3)
npm ERR! Test failed.  See above for more details.
```

**Comment by srepollock** [comment]
Created an [issue](https://github.com/babel/babel/issues/8466) with Babel. I will update here when it has been addressed

**Comment by srepollock** [comment]
Fixed with help from @loganfsmyth on the @Babel @Slack chat

Updated in the commit a4880c5
