### ISSUE TITLE
MessageReceiverComponent causing Engine.instance to throw an undefined error

### ISSUE THREAD

**Issue by srepollock** [srepollock/divine-engine#27]
## What is the Issue

Commit: a5594d8

When working on the MessageReceiverComponent and trying to subscribe to the MessageSystem with a callback function to handle the message, the Engine.instance is not defined.

I'm attempting to call Engine.instance within the MessageReceiverComponent constructor and it appears to be called before the Engine is being initialized.

In the [MessageReceiverComponent spec file](https://github.com/srepollock/divine-engine/blob/feature/message_system/test/components/messagerecievercomponent.spec.ts) you can see that I'm calling `Engine.start()` before initializing the MessageReceiverComponent. This could be an issue with exporting the class then.

## How to duplicate the issue

Pull this commit and run `npm test`

## Screenshots/Console output/Log files

```
> divine-engine@0.2.0 test /Users/Spencer/Documents/git/divine-engine
> mocha --opts mocha.opts test/components/*.spec.ts test/core/*.spec.ts

Debugger listening on ws://127.0.0.1:1123/bb186ffd-47ec-4d97-bc2b-b798e35363bb
For help, see: https://nodejs.org/en/docs/inspector
Debugger attached.
Error Code: 101 Information: Engine instance undefined.
/Users/Spencer/Documents/git/divine-engine/src/core/engine.ts:123
        throw new Error(_logging.ErrorCode.EngineInstanceNull.toString());
        ^

Error: 101
    at Function.get (/Users/Spencer/Documents/git/divine-engine/src/core/engine.ts:70:19)
    at new instance (/Users/Spencer/Documents/git/divine-engine/src/components/messagereceivercomponent.ts:6:16)
    at Suite.<anonymous> (/Users/Spencer/Documents/git/divine-engine/test/components/messagerecievercomponent.spec.ts:17:13)
    at Object.create (/Users/Spencer/Documents/git/divine-engine/node_modules/mocha/lib/interfaces/common.js:112:19)
    at context.describe.context.context (/Users/Spencer/Documents/git/divine-engine/node_modules/mocha/lib/interfaces/bdd.js:40:27)
    at Object.describe (/Users/Spencer/Documents/git/divine-engine/test/components/messagerecievercomponent.spec.ts:7:1)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Module._compile (/Users/Spencer/Documents/git/divine-engine/node_modules/pirates/lib/index.js:83:24)
    at Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Object.newLoader [as .ts] (/Users/Spencer/Documents/git/divine-engine/node_modules/pirates/lib/index.js:88:7)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at /Users/Spencer/Documents/git/divine-engine/node_modules/mocha/lib/mocha.js:250:27
    at Array.forEach (<anonymous>)
    at Mocha.loadFiles (/Users/Spencer/Documents/git/divine-engine/node_modules/mocha/lib/mocha.js:247:14)
    at Mocha.run (/Users/Spencer/Documents/git/divine-engine/node_modules/mocha/lib/mocha.js:576:10)
    at Object.<anonymous> (/Users/Spencer/Documents/git/divine-engine/node_modules/mocha/bin/_mocha:637:18)
    at Module._compile (internal/modules/cjs/loader.js:686:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:742:12)
    at startup (internal/bootstrap/node.js:266:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:596:3)
Waiting for the debugger to disconnect...
npm ERR! Test failed.  See above for more details.
```

**Comment by srepollock** [comment]
This is no longer an issue. As of commit 75ee293b94102373fdf2e3e3b5e6b3278ac1fd72 the DObject appends from MessageReceiver which allows any extender of it to be a message receiver. An issue with this is the circular dependencies and class dependency slippery slope of adding an additional parent class but I believe I can mitigate it starting out. Regardless, this issue is no longer a problem
