### ISSUE TITLE
Fix messagesystem tests

### ISSUE THREAD

**Issue by srepollock** [srepollock/divine-engine#28]
### What is the Issue

The messagesystems tests are erroring with: `TypeError: Super expression must either be null or a function.` After doing some research it looks like the issue is a circular-dependency.

I will try to fix using the fix I talked about in the [GameWindow issue](https://github.com/srepollock/divine-engine/issues/23#issuecomment-427676365).

### How to duplicate the issue

Run `npm test` on commit 7813838.

### Screenshots/Console output/Log files

```
> divine-engine@0.2.0 test /Users/Spencer/Documents/git/divine-engine
> mocha --opts mocha.opts test/components/*.spec.ts test/core/*.spec.ts

/Users/Spencer/Documents/git/divine-engine/node_modules/@babel/runtime/helpers/inherits.js:5
    throw new TypeError("Super expression must either be null or a function");
    ^

TypeError: Super expression must either be null or a function
    at _inherits (/Users/Spencer/Documents/git/divine-engine/node_modules/@babel/runtime/helpers/inherits.js:5:11)
    at /Users/Spencer/Documents/git/divine-engine/src/core/scenemanager.ts:36:26
    at Object.<anonymous> (/Users/Spencer/Documents/git/divine-engine/src/core/scenemanager.ts:170:2)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Module._compile (/Users/Spencer/Documents/git/divine-engine/node_modules/pirates/lib/index.js:83:24)
    at Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Object.newLoader [as .ts] (/Users/Spencer/Documents/git/divine-engine/node_modules/pirates/lib/index.js:88:7)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/Users/Spencer/Documents/git/divine-engine/src/core/engine.ts:7:1)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Module._compile (/Users/Spencer/Documents/git/divine-engine/node_modules/pirates/lib/index.js:83:24)
    at Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Object.newLoader [as .ts] (/Users/Spencer/Documents/git/divine-engine/node_modules/pirates/lib/index.js:88:7)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/Users/Spencer/Documents/git/divine-engine/src/core/dobject.ts:1:1)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Module._compile (/Users/Spencer/Documents/git/divine-engine/node_modules/pirates/lib/index.js:83:24)
    at Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Object.newLoader [as .ts] (/Users/Spencer/Documents/git/divine-engine/node_modules/pirates/lib/index.js:88:7)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/Users/Spencer/Documents/git/divine-engine/src/core/component.ts:1:1)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Module._compile (/Users/Spencer/Documents/git/divine-engine/node_modules/pirates/lib/index.js:83:24)
    at Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Object.newLoader [as .ts] (/Users/Spencer/Documents/git/divine-engine/node_modules/pirates/lib/index.js:88:7)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/Users/Spencer/Documents/git/divine-engine/src/components/flagcomponent.ts:1:1)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Module._compile (/Users/Spencer/Documents/git/divine-engine/node_modules/pirates/lib/index.js:83:24)
    at Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Object.newLoader [as .ts] (/Users/Spencer/Documents/git/divine-engine/node_modules/pirates/lib/index.js:88:7)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/Users/Spencer/Documents/git/divine-engine/src/components/index.ts:1:1)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Module._compile (/Users/Spencer/Documents/git/divine-engine/node_modules/pirates/lib/index.js:83:24)
    at Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Object.newLoader [as .ts] (/Users/Spencer/Documents/git/divine-engine/node_modules/pirates/lib/index.js:88:7)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/Users/Spencer/Documents/git/divine-engine/src/index.ts:1:1)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Module._compile (/Users/Spencer/Documents/git/divine-engine/node_modules/pirates/lib/index.js:83:24)
    at Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Object.newLoader [as .ts] (/Users/Spencer/Documents/git/divine-engine/node_modules/pirates/lib/index.js:88:7)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/Users/Spencer/Documents/git/divine-engine/test/components/flagcomponent.spec.ts:3:1)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Module._compile (/Users/Spencer/Documents/git/divine-engine/node_modules/pirates/lib/index.js:83:24)
    at Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Object.newLoader [as .ts] (/Users/Spencer/Documents/git/divine-engine/node_modules/pirates/lib/index.js:88:7)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at /Users/Spencer/Documents/git/divine-engine/node_modules/mocha/lib/mocha.js:250:27
    at Array.forEach (<anonymous>)
    at Mocha.loadFiles (/Users/Spencer/Documents/git/divine-engine/node_modules/mocha/lib/mocha.js:247:14)
    at Mocha.run (/Users/Spencer/Documents/git/divine-engine/node_modules/mocha/lib/mocha.js:576:10)
    at Object.<anonymous> (/Users/Spencer/Documents/git/divine-engine/node_modules/mocha/bin/_mocha:637:18)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:742:12)
    at startup (internal/bootstrap/node.js:279:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:752:3)
npm ERR! Test failed.  See above for more details.
```

**Comment by srepollock** [comment]
Also, as a task item: remove all `export {<classname> as defualt};` as these can also lead to circular dependencies.

**Comment by srepollock** [comment]
There is another problem running `npm run-script bundle` on 7313838 that gives an error with fs.writeFileSync/readFileSync that is talked about [in this issue](https://github.com/rollup/rollup/issues/897). I'll read up more in the morning; I'm heading to sleep 😴 💩

**Comment by srepollock** [comment]
This cannot be worked on until issue #37 is fixed

**Comment by srepollock** [comment]
As #37 is not going to be looked at for a bit, I'm currently back to working on tests. Currently I'm failing on the file reading in tests, I'm going to just use a set Scene object loaded by TypeScript for the moment. In the future I need to be loading in from the local filesystem but I need to do some research on where/how. Just putting my thoughts down and out there.

**Comment by srepollock** [comment]
Check out commit 4a5a1df1b831caeec84405232c2bef13da4aca9b
